---
title: "CIS 635 Final"
author: "Michael Bordeaux"
date: "2022-12-15"
output: pdf_document
---

```{r include=FALSE}
library(tidyverse)
library(lubridate)
forecast_data <- read_csv("ActualConsumptionForAnalysis.csv")
library(stats)
library(zoo)
library(forecast)
library(ggplot2)

```

```{r include=FALSE}
##create customer objects

customer1 <- filter(forecast_data, Customer == "Customer 1")
customer2 <- filter(forecast_data, Customer == "Customer 2")
customer3 <- filter(forecast_data, Customer == "Customer 3")
customer4 <- filter(forecast_data, Customer == "Customer 4")
customer5 <- filter(forecast_data, Customer == "Customer 5")
customer6 <- filter(forecast_data, Customer == "Customer 6")


```

```{r include=FALSE}
customer1$Date <- mdy(customer1$Date)
customer2$Date <- mdy(customer2$Date)
customer3$Date <- mdy(customer3$Date)
customer4$Date <- mdy(customer4$Date)
customer5$Date <- mdy(customer5$Date)
customer6$Date <- mdy(customer6$Date)
```



```{r include=FALSE}
customer1 <- customer1 %>%
    mutate(week = week(Date),
           year  = year(Date)) %>%
    mutate(week_year = paste(week, year, sep = "-")) %>%
    select(-week,-year) %>% 
    group_by(week_year) %>%
    summarise(Quantity = sum(Quantity))

customer1ts <- ts(customer1$Quantity, frequency = 52, start = c(2021,18), end = c(2022, 15))

```

```{r}
#customer2 <- customer2 %>%
#    mutate(week = week(Date),
#           year  = year(Date)) %>%
#    mutate(week_year = paste(week, year, sep = "-")) %>% 
#    group_by(week_year) %>%
#    summarise(Quantity = sum(Quantity))
```


```{r}
customer2 <- customer2 %>%
    mutate(week = week(Date),
           year  = year(Date)) %>%
    mutate(week_year = paste(week, year, sep = "-")) %>%
    select(-week,-year) %>% 
    group_by(week_year) %>%
    summarise(Quantity = sum(Quantity))

customer2ts <- ts(customer2$Quantity, frequency = 52, start = c(2021,18), end = c(2022, 16))

```

```{r}
customer3 <- customer3 %>%
    mutate(week = week(Date),
           year  = year(Date)) %>%
    mutate(week_year = paste(week, year, sep = "-")) %>%
    select(-week,-year) %>% 
    group_by(week_year) %>%
    summarise(Quantity = sum(Quantity))

customer3ts <- ts(customer3$Quantity, frequency = 52, start = c(2021,18), end = c(2022, 15))
```

```{r}
customer4 <- customer4 %>%
    mutate(week = week(Date),
           year  = year(Date)) %>%
    mutate(week_year = paste(week, year, sep = "-")) %>%
    select(-week,-year) %>% 
    group_by(week_year) %>%
    summarise(Quantity = sum(Quantity))

customer4ts <- ts(customer4$Quantity, frequency = 52, start = c(2021,18), end = c(2022, 15))
```

```{r}
customer5 <- customer5 %>%
    mutate(week = week(Date),
           year  = year(Date)) %>%
    mutate(week_year = paste(week, year, sep = "-")) %>%
    select(-week,-year) %>% 
    group_by(week_year) %>%
    summarise(Quantity = sum(Quantity))

customer5ts <- ts(customer5$Quantity, frequency = 52, start = c(2021,18), end = c(2022, 14))
```

```{r}
customer6 <- customer6 %>%
    mutate(week = week(Date),
           year  = year(Date)) %>%
    mutate(week_year = paste(week, year, sep = "-")) %>%
    select(-week,-year) %>% 
    group_by(week_year) %>%
    summarise(Quantity = sum(Quantity))

customer6ts <- ts(customer6$Quantity, frequency = 52, start = c(2021,18), end = c(2022, 15))
```


```{r}
#customer1 %>% 
#ggplot(aes(x = week_year, y = Quantity, group = week_year)) +
#geom_area(aes(fill = week_year), position = "stack") +
#labs(title = "Quantity Sold: Week Plot", x = "", y = "Sales",
#subtitle = "Customer1") +
#scale_y_continuous()
```
```{r}



c1Arima <- arima(customer1ts,order=c(2,2,1))

c1Forecast <- forecast(c1Arima, h =52)
plot(c1Forecast)

c2Arima <- arima(customer2ts,order=c(2,2,1))

c2Forecast <- forecast(c2Arima, h =52)
plot(c2Forecast)

c3Arima <- arima(customer3ts,order=c(2,2,1))

c3Forecast <- forecast(c3Arima, h =52)
plot(c3Forecast)

c4Arima <- arima(customer4ts,order=c(2,2,1))

c4Forecast <- forecast(c4Arima, h =52)
plot(c4Forecast)

c5Arima <- arima(customer5ts,order=c(2,2,1))

c5Forecast <- forecast(c5Arima, h =52)
plot(c5Forecast)

c6Arima <- arima(customer6ts,order=c(2,2,1))

c6Forecast <- forecast(c6Arima, h =52)
plot(c6Forecast)
```


```{r}
plot(customer1ts)
plot(customer2ts)
plot(customer3ts)
plot(customer4ts)
plot(customer5ts)
plot(customer6ts)

```
```{r}
#regression



# add a regression line to the scatterplot
ggplot(data = customer1ts, aes(x = time(customer1ts), y = customer1ts)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)



# add a regression line to the scatterplot
ggplot(data = customer2ts, aes(x = time(customer2ts), y = customer2ts)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)



# add a regression line to the scatterplot
ggplot(data = customer3ts, aes(x = time(customer3ts), y = customer3ts)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)


# add a regression line to the scatterplot
ggplot(data = customer4ts, aes(x = time(customer4ts), y = customer4ts)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)



# add a regression line to the scatterplot
ggplot(data = customer5ts, aes(x = time(customer5ts), y = customer5ts)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)



# add a regression line to the scatterplot
ggplot(data = customer6ts, aes(x = time(customer6ts), y = customer6ts)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)


```
```{r}
# use the ets() function from the forecast package to fit an ETS model to the time series
etsC1 <- ets(customer1ts)
etsC2 <- ets(customer2ts)
etsC3 <- ets(customer3ts)
etsC4 <- ets(customer4ts)
etsC5 <- ets(customer5ts)
etsC6 <- ets(customer6ts)

etsC1forecast <- forecast(etsC1, h= 12)
etsC2forecast <- forecast(etsC2, h= 12)
etsC3forecast <- forecast(etsC3, h= 12)
etsC4forecast <- forecast(etsC4, h= 12)
etsC5forecast <- forecast(etsC5, h= 12)
etsC6forecast <- forecast(etsC6, h= 12)

plot(etsC1forecast)
plot(etsC2forecast)
plot(etsC3forecast)
plot(etsC4forecast)
plot(etsC5forecast)
plot(etsC6forecast)




```

